### ISSUE TITLE
Storage account domain join automation failing

### ISSUE THREAD

**Issue by danycontre** [Azure/avdaccelerator#280]

**Comment by danycontre** [comment]
01-12-23 15:46:24 - MSFT_ScriptResource:7 - DSC DomainJoinStorage TestScript checking if storage account stavdms17uvw32u is domain joined.
01-12-23 15:46:25 - MSFT_ScriptResource:16 - DSC DomainJoinStorage SetScript Domain joining storage account stavdms17uvw32u
01-12-23 15:46:25 - MSFT_ScriptResource:58 - Forcing group policy updates
01-12-23 15:46:41 - MSFT_ScriptResource:61 - Waiting for domain policies to be applied (2 minutes)
01-12-23 15:48:41 - MSFT_ScriptResource:65 - Turning off Windows firewall. 
01-12-23 15:50:24 - MSFT_ScriptResource:76 - Installing AzFilesHybrid module
01-12-23 15:50:30 - MSFT_ScriptResource:23 - [ERROR] 

Exception             : System.IO.FileNotFoundException: Could not load file or assembly 'Azure.Core, Version=1.25.0.0, 
                        Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot 
                        find the file specified.
                        File name: 'Azure.Core, Version=1.25.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'
                           at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, 
                        ObjectHandleOnStack retTypes)
                           at System.Reflection.RuntimeAssembly.GetExportedTypes()
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly 
                        assembly, String name)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection
                        (Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean 
                        isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String 
                        helpFile, Type& randomCmdletToCheckLinkDemand, Type& randomProviderToCheckLinkDemand)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly 
                        assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean 
                        isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& 
                        helpFile)
                           at 
                        System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly 
                        assembly, PSModuleInfo module)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo 
                        parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly 
                        assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, 
                        ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean 
                        loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, 
                        String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, 
                        ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, 
                        Boolean& moduleFileFound)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModule
                        Options importModuleOptions, String name)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
                        
                        WRN: Assembly binding logging is turned OFF.
                        To enable assembly bind failure logging, set the registry value 
                        [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
                        Note: There is some performance penalty associated with assembly bind failure logging.
                        To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
                        
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Az.Storage\5.3.0\Az.Storage.psm1: 
                        line 93
                        at Request-AzPowerShellModule, 
                        C:\Users\wvdadmin\Documents\WindowsPowerShell\Modules\AzFilesHybrid\0.2.4.0\AzFilesHybrid.psm1: 
                        line 948
                        at <ScriptBlock>, 
                        C:\Users\wvdadmin\Documents\WindowsPowerShell\Modules\AzFilesHybrid\0.2.4.0\AzFilesHybrid.psm1: 
                        line 6496
                        at <ScriptBlock>, C:\Packages\DSCStorageScripts\Script-DomainJoinStorage.ps1: line 89
                        at <ScriptBlock>, <No file>: line 17
                        at ScriptExecutionHelper, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfi
                        guration\DscResources\MSFT_ScriptResource\MSFT_ScriptResource.psm1: line 317
                        at Set-TargetResource, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfigur
                        ation\DscResources\MSFT_ScriptResource\MSFT_ScriptResource.psm1: line 153
PipelineIterationInfo : {}
PSMessageDetails      :

**Comment by danycontre** [comment]
Issue fixed, Azure files are properly joining the domain
